apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard: {}
    database:
      credentialsSecretName: postgres-credentials
      externalDb: false
      postgresDb: dbche
      postgresHostName: postgres
      postgresPort: "5432"
      pvc:
        claimSize: 1Gi
        storageClass: "px-repl2-block" #"gce-ssd-csi"
    devWorkspace:
      ## By default, a user can run only one workspace at a time. You can enable users to run multiple workspaces simultaneously.
      runningLimit: "1"
    devfileRegistry: {}
    imagePuller:
      enable: false
      #spec:
      #  imagePullerImage: registry.redhat.io/devspaces/imagepuller-rhel8@sha256:704522d3c78929941e101f436b7acfee41680a4cb158bfad70dacd5d63198a2a # tag: 3.1-12
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
  devEnvironments:
    secondsOfRunBeforeIdling: -1
    secondsOfInactivityBeforeIdling: 900 # -1 # to disable uncomment
    disableContainerBuildCapabilities: false
    ## until https://github.com/eclipse/che/issues/21760 is addressed
    defaultEditor: https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/che-code/insiders/devfile.yaml
    defaultComponents:
      - name: universal-developer-image
        container:
          image: registry.ford.com/devspaces/udi-ubi8:20221111-2306
          sourceMapping: /projects
          memoryLimit: 6Gi
          memoryRequest: 1Gi
          cpuLimit: 4000m
          cpuRequest: 1000m
          mountSources: true
    defaultNamespace:
      template: <username>-devspaces
      autoProvision: false # <= true by default
    storage:
      pvcStrategy: per-user ## per-user | per-workspace |
      perUserStrategyPvcConfig:
        claimSize: 5Gi
        storageClass: px-repl2-block
      perWorkspaceStrategyPvcConfig:
        claimSize: 5Gi
        storageClass: px-repl2-block
  gitServices:
    github:
      - endpoint: "https://github.ford.com"
        secretName: github-oauth-config
        # https://github.com/eclipse/che/issues/21724
        disableSubdomainIsolation: false
  ## https://github.com/kubermatic/community-components/blob/master/components/eclipse-che/templates/org_v2_checluster.yaml
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
