apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcloud
  labels:
    app.kubernetes.io/name: gcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gcloud
      annotations:
        gcp-openshift-federation-config: |
          {
            "audience": "//iam.googleapis.com/projects/219764264310/locations/global/workloadIdentityPools/sb105-2cf66/providers/sb105-2cf66",
            "credential_source": {
              "file": "/var/run/secrets/openshift/serviceaccount/token",
              "format": {
                "type": "text"
              }
            },
            "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/sa-pipeline@ford-0b080a912fa97c1cf8fb3986.iam.gserviceaccount.com:generateAccessToken",
            "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
            "token_url": "https://sts.googleapis.com/v1/token",
            "type": "external_account"
          }
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway #DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: gcloud
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: gcloud
      serviceAccountName: devspace
      automountServiceAccountToken: false
      enableServiceLinks: false
      shareProcessNamespace: false
      containers:
        - name: gcloud
          image: registry.ford.com/pipelines/gcloud-sdk:410.0.0-20221117-1351
          args: ["tail", "-f", "/dev/null"]
          imagePullPolicy: IfNotPresent
          env:
            - name: http_proxy
              value: "http://internet.gcp.ford.com:83"
            - name: https_proxy
              value: "http://internet.gcp.ford.com:83"
            - name: no_proxy
              value: "localhost,127.0.0.1,.svc,.local,.internal,.googleapis.com,.ford.com,19.0.0.0/8,136.1.0.0/16,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/google/credentials_config.json
            - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
              value: /var/run/secrets/google/credentials_config.json
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
              ephemeral-storage: 128Mi
            requests:
              cpu: 250m
              memory: 250Mi
              ephemeral-storage: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          #livenessProbe:
          #  httpGet:
          #    scheme: HTTP
          #    path: /
          #    port: 8000
          #  initialDelaySeconds: 5
          #  periodSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 10
          #readinessProbe:
          #  httpGet:
          #    scheme: HTTP
          #    path: /
          #    port: 8000
          #  initialDelaySeconds: 5
          #  periodSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 3
          volumeMounts:
            - name: gcp-credentialsrequest-credentials-vol
              readOnly: true
              mountPath: /var/run/secrets/google
            - name: bound-sa-token
              readOnly: true
              mountPath: /var/run/secrets/openshift/serviceaccount
      volumes:
        - name: bound-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: openshift
                  expirationSeconds: 3600
                  path: token
            defaultMode: 420
        #- name: gcp-credentialsrequest-credentials-vol
        #  configMap:
        #    name: gcp-wif-config
        #    items:
        #      - key: google-creds.json
        #        path: credentials_config.json
        #    defaultMode: 420
        #- name: gcp-credentialsrequest-credentials-vol
        #  secret:
        #    secretName: google-creds-dev
        #    defaultMode: 420
        #    optional: true
        - name: gcp-credentialsrequest-credentials-vol
          projected:
            sources:
              - downwardAPI:
                  items:
                    - path: credentials_config.json
                      fieldRef:
                        fieldPath: metadata.annotations['gcp-openshift-federation-config']
